function scr_KeycodeMapCreate()
{
	global.keyLookupMap = ds_map_create();
	ds_map_add(global.keyLookupMap, vk_escape, "Escape");
	ds_map_add(global.keyLookupMap, vk_f1, "F1");
	ds_map_add(global.keyLookupMap, vk_f2, "F2");
	ds_map_add(global.keyLookupMap, vk_f3, "F3");
	ds_map_add(global.keyLookupMap, vk_f4, "F4");
	ds_map_add(global.keyLookupMap, vk_f5, "F5");
	ds_map_add(global.keyLookupMap, vk_f6, "F6");
	ds_map_add(global.keyLookupMap, vk_f7, "F7");
	ds_map_add(global.keyLookupMap, vk_f8, "F8");
	ds_map_add(global.keyLookupMap, vk_f9, "F9");
	ds_map_add(global.keyLookupMap, vk_f10, "F10");
	ds_map_add(global.keyLookupMap, vk_f11, "F11");
	ds_map_add(global.keyLookupMap, vk_f12, "F12");
	ds_map_add(global.keyLookupMap, 145, "Scroll Lock");
	ds_map_add(global.keyLookupMap, vk_pause, "Pause");
	ds_map_add(global.keyLookupMap, 192, "~");
	ds_map_add(global.keyLookupMap, 49, "1");
	ds_map_add(global.keyLookupMap, 50, "2");
	ds_map_add(global.keyLookupMap, 51, "3");
	ds_map_add(global.keyLookupMap, 52, "4");
	ds_map_add(global.keyLookupMap, 53, "5");
	ds_map_add(global.keyLookupMap, 54, "6");
	ds_map_add(global.keyLookupMap, 55, "7");
	ds_map_add(global.keyLookupMap, 56, "8");
	ds_map_add(global.keyLookupMap, 57, "9");
	ds_map_add(global.keyLookupMap, 48, "0");
	ds_map_add(global.keyLookupMap, 189, "-");
	ds_map_add(global.keyLookupMap, 187, "=");
	ds_map_add(global.keyLookupMap, vk_backspace, "Backspace");
	ds_map_add(global.keyLookupMap, 65, "A");
	ds_map_add(global.keyLookupMap, 66, "B");
	ds_map_add(global.keyLookupMap, 67, "C");
	ds_map_add(global.keyLookupMap, 68, "D");
	ds_map_add(global.keyLookupMap, 69, "E");
	ds_map_add(global.keyLookupMap, 70, "F");
	ds_map_add(global.keyLookupMap, 71, "G");
	ds_map_add(global.keyLookupMap, 72, "H");
	ds_map_add(global.keyLookupMap, 73, "I");
	ds_map_add(global.keyLookupMap, 74, "J");
	ds_map_add(global.keyLookupMap, 75, "K");
	ds_map_add(global.keyLookupMap, 76, "L");
	ds_map_add(global.keyLookupMap, 77, "M");
	ds_map_add(global.keyLookupMap, 78, "N");
	ds_map_add(global.keyLookupMap, 79, "O");
	ds_map_add(global.keyLookupMap, 80, "P");
	ds_map_add(global.keyLookupMap, 81, "Q");
	ds_map_add(global.keyLookupMap, 82, "R");
	ds_map_add(global.keyLookupMap, 83, "S");
	ds_map_add(global.keyLookupMap, 84, "T");
	ds_map_add(global.keyLookupMap, 85, "U");
	ds_map_add(global.keyLookupMap, 86, "V");
	ds_map_add(global.keyLookupMap, 87, "W");
	ds_map_add(global.keyLookupMap, 88, "X");
	ds_map_add(global.keyLookupMap, 89, "Y");
	ds_map_add(global.keyLookupMap, 90, "Z");
	ds_map_add(global.keyLookupMap, 219, "[");
	ds_map_add(global.keyLookupMap, 221, "]");
	ds_map_add(global.keyLookupMap, 220, "\\");
	ds_map_add(global.keyLookupMap, 20, "Capslock");
	ds_map_add(global.keyLookupMap, 186, ";");
	ds_map_add(global.keyLookupMap, 222, "'");
	ds_map_add(global.keyLookupMap, 13, "Enter");
	ds_map_add(global.keyLookupMap, 160, "L Shift");
	ds_map_add(global.keyLookupMap, 161, "R Shift");
	ds_map_add(global.keyLookupMap, 162, "L Control");
	ds_map_add(global.keyLookupMap, 163, "R Control");
	ds_map_add(global.keyLookupMap, 164, "L Alt");
	ds_map_add(global.keyLookupMap, 165, "R Alt");
	ds_map_add(global.keyLookupMap, 188, ",");
	ds_map_add(global.keyLookupMap, 190, ".");
	ds_map_add(global.keyLookupMap, 191, "/");
	ds_map_add(global.keyLookupMap, vk_space, "Spacebar");
	ds_map_add(global.keyLookupMap, 93, "Apps");
	ds_map_add(global.keyLookupMap, vk_insert, "Insert");
	ds_map_add(global.keyLookupMap, vk_home, "Home");
	ds_map_add(global.keyLookupMap, vk_pageup, "Page Up");
	ds_map_add(global.keyLookupMap, vk_delete, "Delete");
	ds_map_add(global.keyLookupMap, vk_end, "End");
	ds_map_add(global.keyLookupMap, vk_pagedown, "Page Down");
	ds_map_add(global.keyLookupMap, 144, "Numlock");
	ds_map_add(global.keyLookupMap, 111, "Numpad /");
	ds_map_add(global.keyLookupMap, 106, "Numpad *");
	ds_map_add(global.keyLookupMap, 109, "Numpad -");
	ds_map_add(global.keyLookupMap, vk_numpad0, "Numpad 0");
	ds_map_add(global.keyLookupMap, vk_numpad1, "Numpad 1");
	ds_map_add(global.keyLookupMap, vk_numpad2, "Numpad 2");
	ds_map_add(global.keyLookupMap, vk_numpad3, "Numpad 3");
	ds_map_add(global.keyLookupMap, vk_numpad4, "Numpad 4");
	ds_map_add(global.keyLookupMap, vk_numpad5, "Numpad 5");
	ds_map_add(global.keyLookupMap, vk_numpad6, "Numpad 6");
	ds_map_add(global.keyLookupMap, vk_numpad7, "Numpad 7");
	ds_map_add(global.keyLookupMap, vk_numpad8, "Numpad 8");
	ds_map_add(global.keyLookupMap, vk_numpad9, "Numpad 9");
	ds_map_add(global.keyLookupMap, 110, "Numpad .");
	ds_map_add(global.keyLookupMap, 107, "Numpad +");
	ds_map_add(global.keyLookupMap, vk_left, "Left Arrow");
	ds_map_add(global.keyLookupMap, vk_right, "Right Arrow");
	ds_map_add(global.keyLookupMap, vk_up, "Up Arrow");
	ds_map_add(global.keyLookupMap, vk_down, "Down Arrow");
	ds_map_add(global.keyLookupMap, vk_shift, "Shift");
	ds_map_add(global.keyLookupMap, vk_control, "Control");
}